---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible
    capabilities:
      - NET_ADMIN
      - NET_RAW
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        # TODO
        # ansible_user: admin
        admin_accounts:
          - username: admin2
          - username: admin3
        user_accounts:
          - username: user2
          - username: user3
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
